branches:
  only:
    - master
dist: xenial

addons:
  snaps:
  - hugo

script:
    - hugo
    - echo 'docs.getcaddy.cn' > public/CNAME
       
deploy:
    provider: pages
    repo: caddy-china/docs.getcaddy.cn
    skip-cleanup: true
    github-token: $GITHUB_PUBLISH_TOKEN
    keep-history: true
    local-dir: public
    target-branch: gh-pages
    name: Getcaddy Bot
    verbose: true
    on:
        repo: caddy-china/docs.getcaddy.cn
        branch: master
