baseurl = "https://docs.getcaddy.cn/"
languageCode = "zh-cn"
title = "caddy 中文文档 Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "caddy"
	description = "自动配置 HTTPS 的 HTTP2 服务器"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/mholt/caddy"

	version = "0.10.7"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "/stylesheets/highlight/atom-one-light.css"

	[params.palette]
    	primary = "blue"
    	accent  = "blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "caddy"
	email   = "admin@zuohuadong.cn"


# [[menu.main]]
# 	name   = "Notadd"
# 	url    = "/"
# 	weight = 0

[[menu.main]]
	name   = "关于"
	url    = "introductions/"
	weight = 10


[[menu.main]]
	name   = "开始使用"
	url    = "gettingstarted/"
	weight = 20

[[menu.main]]
	name   = "HOWTO文档"
	url    = "howtos/"
	weight = 30

[[menu.main]]
	name   = "相关技术"
	url    = "technologies/"
	weight = 40

[[menu.main]]
	name   = "二次开发"
	url    = "develops/"
	weight = 50

[[menu.main]]
	name   = "API 文档"
	url    = "apis/"
	weight = 60
[[menu.main]]
	name   = "技术规范"
	url    = "standards/"
	weight = 70
[[menu.main]]
	name   = "使用laradock部署"
	url    = "laradock/"
	weight = 80

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
