baseurl = "https://docs.getcaddy.cn/"
languageCode = "zh-hans"
title = "Caddy 中文文档 Docs"
theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""

[params]
	# General information
	author = "caddy"
	description = "自动配置 HTTPS 的 HTTP2 服务器"
	copyright = "Released under the MIT license"

	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/mholt/caddy"

	version = "0.10.7"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = "/stylesheets/highlight/atom-one-light.css"

	[params.palette]
    	primary = "light-blue"
    	accent  = "light-blue"

    [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"


[social]
	twitter = ""
	github  = "caddy"
	email   = "admin@zuohuadong.cn"


# [[menu.main]]
# 	name   = "Notadd"
# 	url    = "/"
# 	weight = 0

# [[menu.main]]
#	name   = "关于"
#	url    = "introductions/"
#	weight = 10


[[menu.main]]
	name   = "开始使用"
	url    = "get-started/"
	weight = 20

[[menu.main]]
	name   = "HTTP 服务器"
	url    = "http-server/"
	weight = 30

[[menu.main]]
	name   = "标准 HTTP 指令"
	url    = "http/"
	weight = 40

[[menu.main]]
	name   = "DNS 服务商"
	url    = "dns/"
	weight = 50

[[menu.main]]
	name   = "指令／中间件"
	url    = "directive-middleware/"
	weight = 60
[[menu.main]]
	name   = "事件钩子"
	url    = "event-hooks/"
	weight = 70
[[menu.main]]
	name   = "服务器类型"
	url    = "server-type/"
	weight = 80
[[menu.main]]
	name   = "常用教程"
	url    = "examples/"
	weight = 90
	
[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
